Lambda

In [ ]:
x=lambda a,b: a*b
x(1,2)
print(x(3,5))

15


In [ ]:
f=lambda x,y,z=0,w=0: x+2*y+3*z+4*w
print(f(1,2))
print(f(1,2,3))
print(f(1,2,w=3))

5
14
17


In [ ]:
f=lambda x,y=0,z=0,w: x+2*y+3*z+4*w
f(1,2)

SyntaxError: ignored

Express the expression x^3+y^2+5 in lambda

In [ ]:
f=lambda x=1,y=1: pow(x,3)+pow(y,2)+5
f()

7

In [ ]:
songList=["ZOOM","POP","Cupid","Shinzo wo Sasageyo","Way I Am"]

[print(x) for x in songList]

ZOOM
POP
Cupid
Shinzo wo Sasageyo
Way I Am


[None, None, None, None, None]

In [ ]:
newList=[x if x!="Shinzo wo Sasageyo" else "AOT" for x in songList ]
print(newList)

['ZOOM', 'POP', 'Cupid', 'AOT', 'Way I Am']


CLASS

In [16]:
class Account: #class name Account
    pass    #"pass" does nothing

a1=Account()    #constructor called
a2=Account()

a1.name="Anupam"
a1.bal=12000

a2.surname="Kumar"
a2.value=12345
a2.balance=12000
print(Account)
print(a1)
print(f"Name : {a1.name} : {id(a1.name)}")
print(f"Balance : {a1.bal} : {id(a1.bal)}")

print(a2)
print(f"Balance : {a2.balance} : {id(a2.balance)}")
print(f"Value : {a2.value} : {id(a2.value)}")

del(a2.value)   #Removing an attribute

<class '__main__.Account'>
Name : Anupam : 2348911549360
Balance : 12000 : 2348939080688
Balance : 12000 : 2348939080144
Value : 12345 : 2348939080176


In [23]:
class Account:
    def deposit(self, amount):
        self.balance += amount

a=Account()
# print(a.balance)
a.balance=1000
print(a.balance)
a.deposit(12000)    #implicit call
print(a.balance)
# a.balance

Account.deposit(a,1000)
print(a.balance)    #explicit call

1000
13000
14000


In [40]:
class Account:
    def __init__(self,name,accNumber,balance=0):
        self.name = name
        self.accNumber = accNumber
        self.balance = balance
    def deposit(self, amount):
        if amount<=0:
            print("ERROR! Negative deposit amount")
            return
        self.balance += amount
        print(self.balance)
    def withdraw(self, amount):
        if amount<=0:
            print("ERROR! Negative deposit amount")
            return
        if amount>self.balance:
            print("ERROR! Insufficient deposit amount")
            return
        self.balance -= amount
    def display(self):
        print(self.balance)
    def __str__(self):
        return f"Account Name : {self.name} , Balance : {self.balance}"

a=Account("Anupam",123456789,10000)
b=Account("Rishita",123456780)
a.display()
a.withdraw(1000)
a.display()
print(a.__doc__)
print(a.__dict__)
print(a.__module__)
print(a.__str__())
a.deposit(1000)
# a.__str__()

b.display()
print(b.__dict__)

10000
9000
None
{'name': 'Anupam', 'accNumber': 123456789, 'balance': 9000}
__main__
Account Name : Anupam , Balance : 9000
10000
0
{'name': 'Rishita', 'accNumber': 123456780, 'balance': 0}


In [39]:
class Song:
    def __init__(self,songName,duration,album,artist):
        self.songName = songName
        self.duration = duration
        self.album = album
        self.artist = artist
    
    def __str__(self):
        return f"\n Song Name : {self.songName}\n Duration of the song : {self.duration}\n Album Name : {self.album}\n Artist Name : {self.artist}"

    def changeDuration(self,newDuration):
        self.duration = newDuration
    
perfect=Song("PERFECT",3.10,"Divide","Ed Sheeran")
print(perfect.__str__())


 Song Name : PERFECT
 Duration of the song : 3.1
 Album Name : Divide
 Artist Name : Ed Sheeran


INHERITANCE

In [41]:
class CreditAccount(Account):
    pass

In [44]:
b1=CreditAccount("Anupam",12345612)
print(b1)

Account Name : Anupam , Balance : 0


In [3]:
mulNumber=[]
print("Enter 10 numbers : ")
for i in range(10):
    m=int(input("-> "))
    mulNumber.append(m)

for i in range(len(mulNumber)):
    print(f"\nIndex {i} : {mulNumber[i]}")

select=int(input("Enter the index of the number u want to choose : "))
if(select not in range(len(mulNumber))):
    print("\nPlease input an available index")
    select=int(input("Enter the index of the number u want to choose : "))
else:
    n=mulNumber[select]
    print(f"Multiplication table of {n}\n")
    print( "-----------------\n")
    print(f"| {n} * 1 = ",n*1," |\n")
    print(f"| {n} * 2 = ",n*2," |\n")
    print(f"| {n} * 3 = ",n*3," |\n")
    print(f"| {n} * 4 = ",n*4," |\n")
    print(f"| {n} * 5 = ",n*5," |\n")
    print(f"| {n} * 6 = ",n*6," |\n")
    print(f"| {n} * 7 = ",n*7," |\n")
    print(f"| {n} * 8 = ",n*8," |\n")
    print(f"| {n} * 9 = ",n*9," |\n")
    print(f"| {n} * 10 = ",n*10,"|\n")
    print( "-----------------")

Enter 10 numbers : 

Index 0 : 1

Index 1 : 2

Index 2 : 3

Index 3 : 4

Index 4 : 5

Index 5 : 6

Index 6 : 7

Index 7 : 8

Index 8 : 9

Index 9 : 0
Multiplication table of 1

-------------

| 1 * 1 =  1  |

| 1 * 2 =  2  |

| 1 * 3 =  3  |

| 1 * 4 =  4  |

| 1 * 5 =  5  |

| 1 * 6 =  6  |

| 1 * 7 =  7  |

| 1 * 8 =  8  |

| 1 * 9 =  9  |

| 1 * 10 =  10 |

-------------


1. Print the status of a given interface
2. Print all the interface and IP whose status is up
3. Print the count of ethernet interface

In [27]:
wifi={1:{'Interface':'Ethernet0','IP':'1.1.1.1','status':'up'},
      2:{'Interface':'Ethernet1','IP':'2.2.2.2','status':'down'},
      3:{'Interface':'Serial0','IP':'3.3.3.3','status':'up'},
      4:{'Interface':'Serial1','IP':'4.4.4.4','status':'up'}}

print("======================")
print("| Interface | Status |")
print("======================\n")
for key,val in wifi.items():
    # if val['Interface']:
        print(f"| {val['Interface']} : {val['status']} | \n")
print("====================")
print("| Interface |  IP  |")
print("====================\n")
for key,val in wifi.items():
    if val['status']=="up":
        print(f"| {val['Interface']} : {val['IP']} | \n")

count =0
print("====================")
print("| Interface |  IP  |")
print("====================\n")
for key,val in wifi.items():
    if "Ethernet" in val['Interface']:
        count+=1
print(f"Number of Wifi Networks having Ethernet in the name : {count}")

| Interface | Status |

| Ethernet0 : up | 

| Ethernet1 : down | 

| Serial0 : up | 

| Serial1 : up | 

| Interface |  IP  |

| Ethernet0 : 1.1.1.1 | 

| Serial0 : 3.3.3.3 | 

| Serial1 : 4.4.4.4 | 

| Interface |  IP  |

Number of Wifi Networks having Ethernet in the name : 2


Single Inheritance

In [2]:
class School:
    def __init__(self, schoolName):
        self.schoolName = schoolName
    def printName(self):
        print("School Name : ",self.schoolName)
        print("Department Name : ",self.deptName)
class Department(School):
    def __init__(self,deptName,schoolName):
        self.deptName = deptName
        
        School.__init__(self,schoolName)
    # def printName(self):
    #     print("School Name : ",self.schoolName)
    #     print("Department Name : ",self.deptName)
obj_1=Department("Department of Computer Science","School of Sciences")
print(obj_1.schoolName)
obj_1.printName()

School of Sciences
School Name :  School of Sciences
Department Name :  Department of Computer Science


Multiple Inheritance

In [9]:
class Purana:
    def __init__(self,Name):
        self.Name = Name
        print("Purana Class",self.Name)

class Naya1(Purana):
    def __init__(self,Nayaname):
        self.Name = Nayaname
        print(f"Naya class 1 ka naam : {Nayaname}")
        Purana.__init__(self,Nayaname)

class Naya2(Purana):
    def __init__(self,Nayaname):
        self.Name = Nayaname
        print(f"Naya class 2 ka naam : {Nayaname}")
        Purana.__init__(self,Nayaname)
    
obj1=Naya1("Purana dept")
obj2=Naya2("Purana dept")

Naya class 1 ka naam : Purana dept
Purana Class Purana dept
Naya class 2 ka naam : Purana dept
Purana Class Purana dept


Multilevel Inheritance

In [12]:
class Dada:
    def __init__(self,dadaNaam):
        self.dadaNaam = dadaNaam
        print("\nIn Dada Class")
        print("\nPurana Class",self.dadaNaam)

class Papa(Dada):
    def __init__(self,papaNaam):
        print("\nIn Papa Class")
        self.papaNaam = papaNaam
        print(f"\nNaya class 1 ka naam : {papaNaam}")
        Dada.__init__(self,papaNaam)

class Mai(Papa):
    def __init__(self,meraNaam):
        print("\nIn Mai Class")
        self.meraNaam = meraNaam
        print(f"\nNaya class 2 ka naam : {meraNaam}")
        Dada.__init__(self,meraNaam)
    
obj1=Dada("Dada")
obj2=Papa("Papa")
obj2=Mai("Mai")


In Dada Class

Purana Class Dada

In Papa Class

Naya class 1 ka naam : Papa

In Dada Class

Purana Class Papa

In Mai Class

Naya class 2 ka naam : Mai

In Dada Class

Purana Class Mai


In [5]:
days="Mon, Tue, Wed, Thr, Fri, Sat, Sun"
print(days[::5])

MTWTFSS


In [7]:
from abc import ABC,abstractmethod

class Shape():
    @abstractmethod
    def area(self):
        pass

class Rectangle(Shape):
    def __init__(self,x,y):
        self.l=x
        self.b=y
    def area(self):
        return self.l*self.b

class Triangle(Shape):
    def __init__(self,x,y):
        self.b=x
        self.h=y
    def area(self):
        return (self.b*self.h/2)
    
r=Rectangle(10,20)
print("Area of the rectangle : ",r.area())
t=Triangle(10,20)
print("Area of the rectangle : ",t.area())

Area of the rectangle :  200
Area of the rectangle :  100.0


In [4]:
inputTuple=[]
dictReport={}
sells=[]
buys=[]

In [5]:

company=input("Enter your company initials : ")
quantity=float(input("Enter quantity of units : "))
price=float(input("Enter price of units : "))
status=input("Enter your company status (b/s) : ")[0].lower()
temp=(company,quantity,price,status)
inputTuple.append(temp)

print(inputTuple)

for i in inputTuple:
    if(i[3]=='b'):
        temp=(i[1]*i[2],i[1])
        buys.append(temp)
    if(i[3]=='s'):
        temp=(i[1]*i[2],i[1])
        sells.append(temp)
    print(f"Sells : {sells}")
    print(f"Buys : {buys}")
    # for j in i:
    #     if(type(i)==int):
    #         print("Int type")
    #     if (type(i)==float):
    #         print("Float type")                

[('de', 12.0, 21.0, 's')]
[(252.0, 12.0)]
[]


In [16]:
if float==type(3.0):
    print(1)

1


Write a Python program using SET to check the given sentence is Pangram and hetrogram\
 A pangram is a unique sentence in which every letter of the alphabet is used at least once.\
Input : The quick brown fox jumps over the lazy dog\
Output : The string is a pangram\
 Input : geeks for geeks\
Output : The string is not pangram\
 A heterogram is a word, phrase, or sentence in which no letter of the alphabet occurs more than once. Examples:\
 Input : S = "the big dwarf only jumps"\
Output : Yes\
Each alphabet in the string S is occurred only once.\
Input : S = "geeksforgeeks"\
Output : No\
Since alphabet 'g', 'e', 'k', 's' occurred more than once.

In [14]:
isPangram=set()
nAlphabet=0
checkPangram=input("Enter a sentence : ").lower()
isPangram.update(checkPangram)
# print(isPangram)
for i in isPangram:
    if i.isalpha():
        nAlphabet+=1
        # print(nAlphabet)

if (nAlphabet==26):
    print("Sentence is Pangram")
else:
    print("Sentence is not Pangram")

Sentence is Pangram


In [16]:
heterogramList=[]
Input=input("Enter your sentence : ")
heterogramList=Input.split()
print(heterogramList)


['secnuiweiufhwexif', 'shfieohif']


In [3]:
import re

txt="Welcome to The re module"

match=re.match("Wel",txt)
print(match)
search=re.search("he",txt)
print(search.span())
print(search.string)
print(search.group())
fall=re.findall("he",txt)
print(fall)
split=re.split("he",txt)
print(split)
sub=re.sub("T","t",txt)
print(sub)

<re.Match object; span=(0, 3), match='Wel'>
(12, 14)
Welcome to The re module
he
['he']
['Welcome to T', ' re module']
Welcome to the re module


In [6]:
txt="welcome to The re module or concept 08 Aug 2023 module module"
search1=re.findall("[lodu]",txt)
print(search1)

search2=re.findall("\d",txt)
print(search2)

['l', 'o', 'o', 'o', 'd', 'u', 'l', 'o', 'o', 'u', 'o', 'd', 'u', 'l', 'o', 'd', 'u', 'l']
['0', '8', '2', '0', '2', '3']


NUMPY

In [1]:
import numpy as np

In [4]:
a=np.array([1,2,3,4,5,6])
print(a)
print(a[-1])

[1 2 3 4 5 6]
6


In [3]:
rand=np.random.RandomState(32)
x=rand.randint(100,size=10)
print(x)

[87 43  5 54 62 88 19 71 89  3]


In [6]:
ind=[1,3,5,7]
print(x[ind])

[43 54 88 71]


In [9]:
ind = np.array([[3,7,2],[4,5,1]])

print(ind)
print("\n")
print(x[ind])

[[3 7 2]
 [4 5 1]]


[[54 71  5]
 [62 88 43]]


In [11]:
a=np.array([[1,2],[5,6],[7,9]])
print(a)

[[1 2]
 [5 6]
 [7 9]]


In [15]:
a=a.reshape(2,3)
print(a)

[[1 2 5]
 [6 7 9]]


In [16]:
a=np.arange(12).reshape((3,4))
print(a)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


Combined Indexing

In [17]:
a[1, [0,1,2,3]] # show the whole row 1 and columns 0,1,2,3

array([4, 5, 6, 7])

In [23]:
print("\nMinimum from the whole array : ",a.min())
print("\nMaximum from the whole array : ",a.max())
print("\nMinimum for column : ",a.min(axis=0))
print("\nMinimum for row : ",a.min(axis=1))
print("\nMaximum for column : ",a.max(axis=0))
print("\nMaximum for row : ",a.max(axis=1))
print("\nStandard Deviation : ",np.std(a))
print("\nSquare Root : \n\n",np.sqrt(a))
print("\nSum of the array : ",a.sum())
print("\nSum of the array for column : ",a.sum(axis=0))
print("\nSum of the array for row : ",a.sum(axis=1))


Minimum from the whole array :  0

Maximum from the whole array :  11

Minimum for column :  [0 1 2 3]

Minimum for row :  [0 4 8]

Maximum for column :  [ 8  9 10 11]

Maximum for row :  [ 3  7 11]

Standard Deviation :  3.452052529534663

Square Root : 

 [[0.         1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974 2.64575131]
 [2.82842712 3.         3.16227766 3.31662479]]

Sum of the array :  66

Sum of the array for column :  [12 15 18 21]

Sum of the array for row :  [ 6 22 38]


In [24]:
a=np.array([[1,2,3],[10,11,12]])
b=np.array([[11,22,33],[10,11,12]])

print("\nAddition of A and B : \n\n",a+b)
print("\nMultiplication of A and B : \n\n",a*b)
print("\nDivision of A and B : \n\n",a/b)
print("\nMultiplication of A by 3 : \n\n",a*3)


Addition of A and B : 

 [[12 24 36]
 [20 22 24]]

Multiplication of A and B : 

 [[ 11  44  99]
 [100 121 144]]

Division of A and B : 

 [[0.09090909 0.09090909 0.09090909]
 [1.         1.         1.        ]]

Multiplication of A by 3 : 

 [[ 3  6  9]
 [30 33 36]]
